--- 
sequence: 
  lights: 
  - - our
    - light
    - "on"
  - - our
    - lights
    - "on"
room: 
- name: our
  device: 
  - light
  - lights
  - kettle
  - tv
- name: dining
  device:
  - light
  - lights
- name: harry
  device:
  - light
- name: tommy
  device:
  - light
- name: lounge
  device:
  - light
  - lights
- name: kitchen
  device:
  - kettle
  - toaster
  - radio
  - socket
- name: cloakroom
  device:
  - light
- name: hall
  device:
  - light
- name: landing
  device:
  - light
calendar: 'https://www.google.com/calendar/feeds/aar79qh62fej54nprq6334s7ck%40group.calendar.google.com/public/basic'
